# Generated by Django 4.2.20 on 2025-05-07 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.JSONField(default=[], help_text='Enter a list of ingredients in JSON'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.JSONField(default=[], help_text='Enter a list of instructions in JSON'),
        ),
    ]
