# Generated by Django 4.2.20 on 2025-05-07 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_recipe_ingredients_recipe_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.JSONField(default=[], help_text='Enter a list of ingredients as a JSON list of strings'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.JSONField(default=[], help_text='Enter a list of instructions as JSON list of strings'),
        ),
    ]
