# Generated by Django 4.2.20 on 2025-05-07 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_rename_ingredient_recipe_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='url',
            field=models.CharField(help_text='The original recipe URL', max_length=2000, null=True),
        ),
    ]
