# Generated by Django 4.2.20 on 2025-05-07 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_recipe_borrower'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='borrower',
            new_name='creator',
        ),
    ]
