# Generated by Django 4.2.20 on 2025-05-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_rename_borrower_recipe_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='url',
            field=models.CharField(blank=True, help_text='The original recipe URL', max_length=2000, null=True),
        ),
    ]
