# Generated by Django 4.2.20 on 2025-05-07 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_recipe_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cook_time',
            field=models.IntegerField(default=0, help_text='Enter the minutes of cook time'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(default=[], help_text='Select ingredients for this recipe', to='catalog.ingredient'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.ManyToManyField(default=[], help_text='Select instructions for this recipe', to='catalog.instruction'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time',
            field=models.IntegerField(default=0, help_text='Enter the minutes of prep time'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servings',
            field=models.CharField(default='', help_text='Enter the number of servings', max_length=32),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tag',
            field=models.ManyToManyField(default=[], help_text='Select a tag for this recipe', to='catalog.tag'),
        ),
    ]
